"""Infrastructure component for building runall.csh script content.

This is a pure builder: it takes parameters and produces a script string.
No filesystem mutation; directory creation handled elsewhere if needed.
"""
from __future__ import annotations
from typing import Dict, Any, List
from pathlib import Path

class RunAllScriptBuilder:
    REQUIRED_BASE_FLAGS = ["-tmqc", "-nostop"]

    def build(self, cell: str, project: str, subproject: str, params: Dict[str, Any]) -> str:
        """Return runall.csh content.

        Parameters:
            cell: Cell name
            project/subproject: For debug path fallback
            params: Dictionary of user-selected options; keys reflect legacy UI fields.
        """
        lines: List[str] = [
            "#!/bin/csh -f",
            "# Generated by web Timing QC page (migrated builder)",
            "# Edit cautiously if re-running manually.",
            "",
            "# Primary command (legacy style):",
            "TimingCloseBeta.py \\",
            f"                -cell {cell} \\",
        ]
        # Base flags (-update optional) + required flags
        if params.get("update"):
            lines.insert(len(lines)-1, "                -update -tmqc \\")
        else:
            lines.insert(len(lines)-1, "                -tmqc \\")
        lines.insert(len(lines)-1, "                -nostop \\")

        # Append optional flags preserving ordering
        def add_flag(flag: str, value: Any, formatter=lambda v: v):
            if value is not None and value is not False and value != "":
                lines.append(f"                {flag} {formatter(value)} \\")

        add_flag("-specs", params.get("qcplan"))
        add_flag("-data", params.get("data"))
        
        # Handle multiple datastore entries
        datastore_list = params.get("datastore")
        if datastore_list and isinstance(datastore_list, list):
            for ds in datastore_list:
                if ds:  # Only add non-empty values
                    lines.append(f"                -datastore {ds} \\")
        
        add_flag("-common_source", params.get("common_source"))
        add_flag("-include", params.get("include"))
        add_flag("-index", params.get("index"), lambda v: f'"{v}"')
        if params.get("adjustment"):
            lines.append("                -adjustment \\")
        if params.get("no_wf"):
            lines.append("                -noWF \\")
        if params.get("xtalk_rel_net"):
            lines.append("                -xtalkRelNet \\")
        add_flag("-xtalk", params.get("xtalk"))
        add_flag("-hierarchy", params.get("hierarchy"))
        add_flag("-verbose", params.get("verbose"))
        add_flag("-primesim", params.get("primesim"))
        add_flag("-hspice", params.get("hspice"))

        # Debug path (should be absolute; caller creates empty dir if needed)
        debug_path = params.get("debug_path")
        if debug_path:
            lines.append(f"                -debug {debug_path} \\")

        add_flag("-netlist", params.get("netlist"))
        add_flag("-refdata", params.get("ref_data"))
        add_flag("-phase", params.get("phase"), lambda v: f'"{v}"')

        # Strip trailing backslash on final option line
        if lines[-1].rstrip().endswith("\\"):
            lines[-1] = lines[-1].rstrip().rstrip("\\").rstrip()

        lines.append("")
        lines.append("# Notes:")
        lines.append("#  - Netlist for TMQC : ../../../extr/<cell>/rcxt/checkout/tmqc/ (verify path)")
        lines.append("#  - Provide timing.paths in nanotime simulation directory if required")
        lines.append("")
        return "\n".join(lines) + "\n"
